### ISSUE TITLE
Pre-release for phantomjs 2.0.0

### ISSUE THREAD

**Issue by stebln** [qa/arquillian-phantom-binary#6]
Hi,

knowing that there are build problems with the linux version of phantomjs which still have to be resolved, I was wondering if it would be possible to create a pre-release for phantomjs version 2.0.0? Could be called 2.0.0-rc1 or similar.

Thanks,

Steffen

**Comment by smiklosovic** [comment]
@MatousJobanek

**Comment by MatousJobanek** [comment]
Hi @stebln, 
and what would you expect from this pre-release? That it would contain PhantomJS 2.0.0 only for windows and mac and for the linux it would keep the old version?

**Comment by stebln** [comment]
Yes, even though I am not sure if it would be better to not offer linux binaries at all in this release to avoid confusion or as you say add the last stable version - depends on what is acceptable

**Comment by lfryc** [comment]
Let's get 2.0 release out and wait for 2.1 to cover linuxes (it could be in ~January): https://github.com/ariya/phantomjs/issues/12970#issuecomment-169539354

**Comment by stfnlutter** [comment]
Closing this issue as the releases are available, thanks for your work on this!
